### ISSUE TITLE
SCP-YC-007.html的bug太多了！！！！！

### ISSUE THREAD

**Issue by chenmaster05** [SCP-YC/SCP-YC.github.io#3]
1. 自动换行失效
2. 第二段落全文粗体
3. 第三段落”暂定“需删减
4. 采访折叠栏展开后无法折叠
5. 所有日记展开前无问号
6. ”日记一“无引用栏
7. 日记10、13、17、31开头没回车
8. 所有日记结尾没回车
9. 日记二十六划线左右存在未转换波浪线

**Comment by 0And1Story** [comment]
1. 没有自动换行，折叠块需要手动换行；
2. 可以手动修改；
3. （这个应该你自己改吧！；
4. 你没有写折叠信息；
5. 自己修改；
6. 自己修改；
7. 自己修改；
8. 自己修改；
9. 自己修改。

**（综合决定：不予修改）**
